"""crear tablas iniciales

Revision ID: 6ddab0416865
Revises: 
Create Date: 2025-11-22 14:39:18.587041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ddab0416865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrito_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('supermercado', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resenas',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=True),
    sa.Column('producto_key', sa.String(length=100), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_resena')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('votos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['resenas.id_resena'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('user_id', 'review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('usuarios')
    op.drop_table('resenas')
    op.drop_table('carrito_items')
    # ### end Alembic commands ###
