"""estado inicial

Revision ID: fd5857ee9f7f
Revises: 
Create Date: 2025-11-22 15:49:27.743037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5857ee9f7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.alter_column('nombre_usuario',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('producto_key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('comentario',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_resenas_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_resenas_producto_key'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resenas_producto_key'), ['producto_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_resenas_id_usuario'), ['id_usuario'], unique=False)
        batch_op.alter_column('comentario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('producto_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('nombre_usuario',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
